# Generated by Django 4.2.1 on 2025-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Single character item identifier (e.g., A, B).', max_length=1, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of a single item.', max_digits=10)),
                ('special_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity for special price.', null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special price for the specified quantity.', max_digits=10, null=True)),
            ],
        ),
    ]
